### ISSUE TITLE
the app cannot start even by building cloning and running or by just running the binary. 

### ISSUE THREAD

**Issue by devtestmrx** [ozankaraali/QiTV#1]
Traceback (most recent call last):
  File "/home/Desktop/learning/workspace/STB_IPTV/QiTV/main.py", line 28, in <module>
    prevent_sleep()
  File "/home/Desktop/learning/workspace/STB_IPTV/QiTV/sleep_manager.py", line 32, in prevent_sleep
    prevent_sleep_linux()
  File "/home/Desktop/learning/workspace/STB_IPTV/QiTV/sleep_manager.py", line 110, in prevent_sleep_linux
    if reply.type() == reply.ReplyMessage:
AttributeError: 'PySide6.QtDBus.QDBusMessage' object has no attribute 'ReplyMessage'

**Comment by ozankaraali** [comment]
Thanks, since you can build from scratch, I suggest you to disable sleep manager code in main.py. Hopefully it will fix. I don’t test on linux and seems sleep prevention function has missing function signatures, I will fix it later.

**Comment by ozankaraali** [comment]
Test this and let me know if it fixes.
https://github.com/ozankaraali/QiTV/releases/tag/release-6ec13ed
