### ISSUE TITLE
App Doesn't Open in M1

### ISSUE THREAD

**Issue by ChaosCrusader** [ozankaraali/QiTV#19]
**System**: M1 Air
**QiTV Version**: v1.5.8 (Universal)

The app immediately closes after its opening on the dock.

**Comment by ozankaraali** [comment]
Wait a bit more

**Comment by ChaosCrusader** [comment]
```
vlc: unknown option or missing mandatory argument `--http-user-agent=Mozilla/5.0 (QtEmbedded; U; Linux; C) AppleWebKit/533.3 (KHTML, like Gecko) MAG200 stbapp ver: 2 rev: 250 Safari/533.3'
Try `vlc --help' for more information.
Traceback (most recent call last):
  File "main.py", line 30, in <module>
  File "video_player.py", line 67, in __init__
AttributeError: 'NoneType' object has no attribute 'media_player_new'
[PYI-42245:ERROR] Failed to execute script 'main' due to unhandled exception: 'NoneType' object has no attribute 'media_player_new'
[PYI-42245:ERROR] Traceback:
Traceback (most recent call last):
  File "main.py", line 30, in <module>
  File "video_player.py", line 67, in __init__
AttributeError: 'NoneType' object has no attribute 'media_player_new'


Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...       1 completed.

[Process completed]
```

**P.S**: This has been the quickest reply to a github issue ever, you are awesome

**Comment by ozankaraali** [comment]
Sorry for that, I thought it was because it does some update check and setting creation in the startup procedure, but this time it's not about that.

Try this one for now (which was my favorite, stable release), hopefully it will work for you until I patch in the next one.
https://github.com/ozankaraali/QiTV/releases/download/v1.4.4/qitv-macos-universal.zip

It shouldn't be saying unknown option for that one, but this line is also redundant. So we can patch that later on.

Meanwhile if you know how to develop
https://github.com/ozankaraali/QiTV/blob/ea717bda7ec9ee7e66b2256c8fccf557e200a366/video_player.py#L64
just delete the http-user-agent argument from here and try to run from scratch.

Thanks for the note, I am glad to hear.

**Comment by ChaosCrusader** [comment]
Even v1.4.4 is having some issues

```
Traceback (most recent call last):
  File "main.py", line 30, in <module>
  File "video_player.py", line 42, in __init__
AttributeError: 'NoneType' object has no attribute 'media_player_new'
[53686] Failed to execute script 'main' due to unhandled exception: 'NoneType' object has no attribute 'media_player_new'
[53686] Traceback:
Traceback (most recent call last):
  File "main.py", line 30, in <module>
  File "video_player.py", line 42, in __init__
AttributeError: 'NoneType' object has no attribute 'media_player_new'


Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

Don't really understand app development tbh, so for the time being your older project PiTV works for me ;)

**Comment by dlm21** [comment]
I'm having the same issues on CachyOS (Arch) Linux, the vlc arg error on 1.5.8 and the no attribute 'media_player_new' error on 1.4.4 . FWIW I have vlc 3.0.21 installed. Looks like it's happening shortly after being unable to find /tmp/_MEIclCk2v/vlc/plugins/plugins.dat (seen in strace output). I installed python-vlc but it had no effect, I'm guessing due to it being fatpacked in to the binary and not looking at system files

**Comment by ozankaraali** [comment]
Hahah, I had no idea and I wonder why this issue waited until this moment :D 
It was working for me in my both computers but you’re right, I will be fixing that soon and let you know, thanks for the feedback :)

**Comment by ozankaraali** [comment]
Please try 
https://github.com/ozankaraali/QiTV/releases/tag/v1.5.9
and let me know if that helps

**Comment by ozankaraali** [comment]
Closing due to inactivity, lmk if the issue persists.
